const POPULAR_SLOTS = [
    "Sweet Bonanza",
    "Sweet Bonanza 1000",
    "Sugar Rush",
    "Sugar Rush 1000",
    "Gates of Olympus",
    "Gates of Olympus 1000",
    "Fruit Party",
    "The Dog House",
    "The Dog House Megaways",
    "Release the Kraken",
    "Release the Kraken Megaways",
    "Beware The Deep Megaways",
    "Trees of Treasure",
    "Wildies",
    "Dragon King Hot Pots",
    "Barnyard Megahays Megaways",
    "Le Viking",
    "6 Jockers",
    "Yeti Quest",
    "Candy Corner",
    "Sweet Rush Bonanza",
    "Book of Dead",
    "Legacy of Dead",
    "Razor Shark",
    "Razor Returns",
    "Wanted Dead or a Wild",
    "Retro Tapes",
    "Jammin' Jars",
    "Mental",
    "San Quentin",
    "Starlight Princess",
    "Starlight Princess 1000",
    "Tome of Madness",
    "Zeus vs Hades",
].sort();

export { POPULAR_SLOTS };
